# FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.1
FROM docker.elastic.co/elasticsearch/elasticsearch:5.3.0

# RUN apt-get update  && \
#    apt-get install -y jq vim

# EXPOSE 9200
# EXPOSE 9300
